# Generated by Django 3.0.4 on 2020-03-22 21:44

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail_svgmap.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('section_slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'])),
                ('int_order', models.IntegerField(default=170)),
                ('body', wagtail.core.fields.StreamField([('column_about_block', wagtail.core.blocks.StreamBlock([('about_content', wagtail.core.blocks.StreamBlock([('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('width', wagtail.core.blocks.IntegerBlock(max_value=4000, min_value=0, required=False)), ('height', wagtail.core.blocks.IntegerBlock(max_value=4000, min_value=0, required=False)), ('class_name', wagtail.core.blocks.CharBlock(required=False))], classname='full title', required=False, template='About/block_templates/image_block.html')), ('rich_field_text', wagtail.core.blocks.RichTextBlock(required=False)), ('svg_image', wagtail.core.blocks.StructBlock([('svg_image', wagtail.core.blocks.StructBlock([('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))], required=True)), ('class_name', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.CharBlock(required=False))], template='CustomBlock/custom_image_svg_block.html')), ('grid_block', wagtail.core.blocks.StructBlock([('icon_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('svg_image', wagtail.core.blocks.StructBlock([('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))], required=True)), ('class_name', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.CharBlock(required=False))], template='CustomBlock/custom_image_svg_block.html'), template='CustomBlock/custom_list_icon_block.htm')), ('class_name', wagtail.core.blocks.CharBlock(required=False))], template='CustomBlock/custom_grid_icon_block.html'))]))], required=False))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
