# Generated by Django 3.0.6 on 2020-05-25 01:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_svgmap.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_aboutpageindex_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpageindex',
            name='icon_page',
            field=wagtail.core.fields.StreamField([('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))], default=None),
            preserve_default=False,
        ),
    ]
