# Generated by Django 3.0.6 on 2020-05-25 01:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_svgmap.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0003_aboutpageindex_icon_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpageindex',
            name='icon_page',
        ),
        migrations.AddField(
            model_name='aboutpageindex',
            name='icon',
            field=wagtail.core.fields.StreamField([('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))], default=0),
            preserve_default=False,
        ),
    ]
