# Generated by Django 3.0.6 on 2020-05-25 02:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_svgmap.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0004_auto_20200525_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpageindex',
            name='icon',
            field=wagtail.core.fields.StreamField([('svg_image', wagtail.core.blocks.StructBlock([('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))], required=True)), ('class_name', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.CharBlock(required=False))]),
        ),
    ]
