# Generated by Django 3.0.6 on 2020-05-25 02:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_svgmap.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0005_auto_20200525_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpageindex',
            name='icon',
            field=wagtail.core.fields.StreamField([('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))], blank=True, null=True),
        ),
    ]
