# Generated by Django 3.0.6 on 2020-05-25 02:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_svgmap.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0006_auto_20200525_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpageindex',
            name='icon',
            field=wagtail.core.fields.StreamField([('lemoncake', wagtail.core.blocks.StructBlock([('svg_image', wagtail.core.blocks.StructBlock([('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))], required=True)), ('class_name', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.CharBlock(required=False))], blank=True, max_num=1, min_num=0, required=False))], blank=True, null=True),
        ),
    ]
