# Generated by Django 3.0.6 on 2020-05-26 03:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_svgmap.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0008_auto_20200525_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpageindex',
            name='icon',
        ),
        migrations.AddField(
            model_name='aboutpageindex',
            name='page_icon',
            field=wagtail.core.fields.StreamField([('icon_page', wagtail.core.blocks.StructBlock([('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))]))], default=None),
            preserve_default=False,
        ),
    ]
