# Generated by Django 3.1.2 on 2020-10-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20201017_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='git_hub_account',
            field=models.TextField(blank=True, null=True),
        ),
    ]
