# Generated by Django 3.1.2 on 2020-10-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_git_hub_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='git_api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
