# Generated by Django 3.1.2 on 2020-10-21 01:29

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_projectpageindex_page_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='project_name'),
        ),
    ]
