# Generated by Django 3.1.2 on 2020-10-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20201021_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='project',
            name='show_case',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
