# Generated by Django 3.1.2 on 2020-10-28 14:36

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20201027_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
