# Generated by Django 3.1.2 on 2020-10-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_auto_20201028_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='related_categories', to='Projects.ProjectCategory'),
        ),
    ]
