# Generated by Django 3.1.2 on 2020-11-01 18:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_projectcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='coral', max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='ProjectCategoryOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_categories', to='Projects.project')),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.projectcategory')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
