# Generated by Django 3.1.2 on 2020-11-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0013_auto_20201101_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.AddField(
            model_name='project',
            name='_categories',
            field=models.ManyToManyField(blank=True, through='Projects.ProjectCategoryOrderable', to='Projects.ProjectCategory'),
        ),
    ]
